Set Profile=2
A Path=F:\OfficePC_Update\!FB\!VisualFreeBasic\VisualFreeBasic5.8.1
B Path=F:\OfficePC_Update\!FB\!VisualFreeBasic\VisualFreeBasic5.8.2
Compare Data=1
Compare Mode=0
Increment=false
Duplication=false
Synchronization=true
Copy Empty Path=true
Log Nothing=false
Log Memory=true
Log File=false
Log FileName=FileSync.log